# Generated by Django 3.1.1 on 2020-10-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisors',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisors',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
