# Generated by Django 3.1.1 on 2020-10-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0003_auto_20201005_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inusemachine',
            old_name='item_id',
            new_name='item',
        ),
    ]
