# Generated by Django 3.1.1 on 2020-10-07 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0005_auto_20201005_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='user_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makerlab.registereduser', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='inusemachine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makerlab.registereduser', to_field='user_id'),
        ),

        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makerlab.registereduser', to_field='user_id'),
        ),
    ]
