# Generated by Django 3.1.1 on 2020-10-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0008_auto_20201011_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='warranty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
