# Generated by Django 3.1.1 on 2020-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0012_inusemachine_time_used_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
