# Generated by Django 3.1.2 on 2020-10-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0013_item_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=200, unique=True)),
                ('query_sql', models.TextField(unique=True)),
            ],
        ),
    ]
