# Generated by Django 3.1.1 on 2020-10-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0014_auto_20201013_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='makerlab.vendor', to_field='vendor_name'),
            preserve_default=False,
        ),
    ]
