# Generated by Django 3.1.1 on 2020-10-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0015_auto_20201013_2133'),
        ('makerlab', '0014_savedquery'),
    ]

    operations = [
    ]
