# Generated by Django 3.1.1 on 2020-10-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0016_merge_20201014_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
