# Generated by Django 3.1.1 on 2020-10-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerlab', '0017_auto_20201014_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inuseitem',
            old_name='time_used_id',
            new_name='entry_exit_id',
        ),
        migrations.RemoveField(
            model_name='inuseitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='email',
        ),
    ]
